### PR TITLE
WIP - HiMD build

### PR DESCRIPTION
**Pull request by deenine**
Do not merge, rough & ready. 

Requires a modified himdcli that outputs json.

### CODE REVIEW

**Comment by Invictaz** [comment]
Really great. I hope @cybercase is reading this. 

@deenine does it have support for ATRAC3+ ?

**Comment by deenine** [comment]
Ive spent a little more time on this today, the switch between hi-md/md now works, although its not pretty...and for some reason the play/pause/skip buttons are vertical now!

Ive sent a bunch of mp3s over to my RH1 and they work, currently using VBR mp3s from amazon's autorip. Some tracks fail to play on the device, even after transcoding to mp3 128 or mp3 320, but other tracks converted from wav using the same ffmpeg work.

There are some limitations to the himd support in linux-minidisc:
- No CLI support for titling or erasing tracks, may be present in code
- No support for erasing discs or getting capacity on mac (beacuse there is no generic scsi driver on OSX)
- MP3 transfer to device only - Hi-SP and Hi-LP are not implemented in linux-minidisc (more information here: https://wiki.physik.fu-berlin.de/linux-minidisc/doku.php?id=himddiskformat#encryption)
- Limited device support - unclear if it is RH1 only, or all 2nd/3rd gen devices

The CLI supports transfer of tracks back to the PC, but I havent added this to pmd yet, I will do when i get some time. 

Im not sure if it is worth continuing/releasing this given the limitations above. @gavinbenda I suggest we ask the facebook group how many people use/want to use himd and what functionality is useful, its not something I've ever used.

@Invictaz The linux-minidisc project has talked about working on ATRAC3+, but it doesnt look like they have made progress on this, it is certainly not released currently.

**Comment by Invictaz** [comment]
@deenine according to their official Wiki (which is years old) read support for ATRAC3+ is implemented

http://manpages.ubuntu.com/manpages/bionic/man1/himdcli.1.html

**Comment by Invictaz** [comment]
@deenine the encryption is not publicyly talked about (but in the mailinglist there was talk about). You should message @glaubitz

**Comment by Invictaz** [comment]
@deenine Some test files

https://github.com/vuori/linux-minidisc/commit/77f4d5e6b9786d779b9e91125c836b6798be3ba7

**Comment by Invictaz** [comment]
@deenine Download (getting mp3 files from the device to your pc) should also work with mp3's

https://github.com/ticky/linux-minidisc/blob/280923a0acfbaaf340f1e8bd0a0d38a0a5b0a92b/libhimd/mp3download.c

**Comment by Invictaz** [comment]
@deenine uploading MP3 (from Hi-MD to PC) should be available.

https://github.com/ticky/linux-minidisc/tree/e89aea5f7e3cdd94b46c2a9a5671f0088c916caf/qhimdtransfer

**Comment by Invictaz** [comment]
@deenine maybe the correct codec is not set when transferring mp3 files to the device. See here:

https://github.com/thp/linux-minidisc/commit/8733a89c2303b1176ef9dc27512bf3f17bd4331d

**Comment by Invictaz** [comment]
@deenine SCSI on OSX:

https://lists.fu-berlin.de/htdig/linux-minidisc/2010-May/msg00012.html

**Comment by Invictaz** [comment]
@deenine uploading Hi-SP and LP tracks should work fine already for 10 years.

https://lists.fu-berlin.de/htdig/linux-minidisc/2010-March/msg00035.html

However tracks should be recorded with the same device as being downloaded on. From another device (the Sony encryption) is not fully understood yet.

**Comment by deenine** [comment]
@Invictaz when i said 'no atrac3+' i meant no transfer to device. Currently this platinum-md patch does not support transfer from hi-md to PC at all, I didnt think it was as common a use-case, although it should be relatively simple to add because the RH1 md-PC patch is already in the interface.

Once I have had time to get mp3 transfers to the RH1 stable, i think the next step is to test on other RH* models, before deciding if we continue. I am still not sure there is enough functionality/compatibility with hi-md to be worth bothering with.

**Comment by deenine** [comment]
Added a convert to wav, then convert to mp3 stage for all tracks before transfering to get around the problem where some tracks were unplayable on the RH1. Just converting VBR to CBR 128/256/320kb mp3 didnt fix the issue, unsure if this is a himdcli or firmware issue (or some combination of them and ffmpeg/lame).

Whatevs, it works, just takes a little longer. Also added some better status outputting.

**Comment by Invictaz** [comment]
@deenine if you have read my extensively researched comments and links I posted that AT3+ transfer to the device is possible.

Also if you check the repo's I mentioned the MPEG header needs to be set correctly otherwise it fails. That removes the intermediate step of converting to WAV first. https://github.com/gavinbenda/platinum-md/pull/67#issuecomment-731841297

**Comment by deenine** [comment]
> @deenine if you have read my extensively researched comments and links I posted that AT3+ transfer to the device is possible.

Ive had a look through your links, but dont see anything confirming that AT3+ to the device is possible, which one should I be looking at? There is a page in the wiki that describes it, but lists the keygen as a blackbox, so I think this is either unknown or at least not public.


> Use case is already viable since there is no opensource way of transfering with a GUI. QHiMDtransfer is long outdated and SonicStage adds DRM. So we absolutely need your developments in order to have it working on modern systems.

Thats positive! I'll keep having a play.


> Also if you check the repo's I mentioned the MPEG header needs to be set correctly otherwise it fails. That removes the intermediate step of converting to WAV first I hope. [#67 (comment)](https://github.com/gavinbenda/platinum-md/pull/67#issuecomment-731841297)

This patch is present in Gavin's linux-minidisc fork that I am working from, see here, etc: https://github.com/gavinbenda/linux-minidisc/blob/master/himdcli/himdcli.c#L425 So I dont believe that is the problem. My current guess is that there is an issue with the ID3 data (I am guessing the ffmpeg VBR->CBR passes the id3 data straight through), but I havent tested this yet.


> Regarding other RH* devices: transfer of AT3+ to and from those devices is supported, mp3 is supported. Only standard (Net)MD upload is limited to RH1. Don't forget about NH1 which is the almost identical twin to the RH1, which also supports AT3+ upload according to the manual:
> 
> http://www.minidisc.org/manuals/sony/Sony_MZ-NH1_operation_manual.pdf
> 
> Unclear is if the RH1 is the only device that permits AT3+ uploads from ALL sources, not only the analog sources.

Isnt the NH1 a first gen himd device and the RH1 a third gen device?

**Comment by Invictaz** [comment]
@deenine the root key is linked in that Github. If the root key is present than the rest can be done. AFAIK the original QHiMDtransfer has support for AT3 transfers. So it should be possible.

From what I have seen there is no such thing as ID3 present in the forks, that was omitted in the MP3 transfers. So ID3 support would need to be developed from the ground up and then upstreamed to mainline linux-minidisc.

The difference between the generations is not very clear to me. AFAIK the third and last gen RH1 has OLED displays and unlimited uploading of old minidisc discs. The first gen was only the HI-SP and Hi-LP. Second gen added photo support:
according to http://www.minidiscforum.de/mdfaq/1/1_2.htm

**Review by Invictaz — COMMENTED** [review]
Please include to download in the original format without conversion such as .AT3 or .AA3 (ATRAC3) for AT3Plus there is .OMA but that might be the DRM version Sony uses.

**Comment by deenine** [comment]
> Please include to download in the original format without conversion such as .AT3 or .AA3 (ATRAC3) for AT3Plus there is .OMA but that might be the DRM version Sony uses.

As here: https://github.com/gavinbenda/platinum-md/pull/62#issuecomment-716446924

> @deenine the root key is linked in that Github. If the root key is present than the rest can be done. AFAIK the original QHiMDtransfer has support for AT3Plus transfers. So it should be possible.

I dont think QHiMDtransfer supports AT3+ transfers to the device, but I will review the source in a bit more detail sometime. This branch now supports AT3+, LPCM and AT3 transfers from the device to PC, but only supports MP3 to the device. I dont anticipate this changing in the near future unless there is existing functionality that I have missed.

> From what I have seen there is no such thing as ID3 present in the forks, that was omitted in the MP3 transfers. So ID3 support would need to be developed from the ground up and then upstreamed to mainline linux-minidisc.

himdcli passes the mp3 file directly to the device, so any ID3 information present in the source file is present when transfered. 

> The difference between the generations is not very clear to me. AFAIK the third and last gen RH1 has OLED displays and unlimited uploading of old minidisc discs. The first gen was only the HI-SP and Hi-LP. Second gen added photo support:
> according to http://www.minidiscforum.de/mdfaq/1/1_2.htm

According to minidisc.org, MP3 support came along in the second generation recorders (which all begin `MZ-RH`) http://www.minidisc.org/himd_table.html Unclear which players support mp3, as this does not appear to be a complete list

**Comment by Invictaz** [comment]
The MZ-DH10P is is also a second gen device that supports MP3. Sometimes they appear on secondhand sites such as Ebay. For the rest it is indeed RH* devices.

MP3 upload is here (I guess)

https://github.com/glaubitz/linux-minidisc/blob/79799aadecc250d87e68ae1d07f688d7febd447e/himddump/himddump.c

Also see this for mp3 download: 

https://github.com/glaubitz/linux-minidisc/commit/79799aadecc250d87e68ae1d07f688d7febd447e

and

https://github.com/glaubitz/linux-minidisc/commit/5a5c5515f2a938d7589232fa470f98dfe959a7ad


himd.c - Main library code providing functions on the top level himd object
encryption.c - All the stuff related to cryptography and key determination
mdstream.c - Functions to read/write audio streams in the atdataXX.hma file
**trackindex.c - Functionality to encode/decode track metadata**


According to QHiMDtransfer there is the metadata transfer file that makes MP3's playback on the devices. Have you looked at it?

----

AT3+ download is crucial to keep the format alive. 

Remember that there is a second root key needed for Hi-SP and Hi-LP, I don't know who has it but probably @thp or @tharp

Also found this on writing AT3+ to pc

https://github.com/glaubitz/linux-minidisc/blob/9065acf1e9d87319661c83c4dc154605fee827a0/himdtest/himdtest.c#L246

and

https://github.com/glaubitz/linux-minidisc/blob/a3e2bd5f2d16b836fd3094f839b4ba8613c2a67b/libhimd/mdstream.c

**Comment by Invictaz** [comment]
@deenine Here's more about the key being used

https://groups.google.com/g/linux.debian.bugs.dist/c/_kLHBwpnXKs/m/cV4Yj-R2NtAJ?pli=1

**Comment by Invictaz** [comment]
Implementing DES and 3DES in JS:

https://github.com/hosseinmd/data-crypto

**Comment by Invictaz** [comment]
@deenine 

More SCSI is here: https://wiki.physik.fu-berlin.de/linux-minidisc/doku.php?id=himdscsi

**Comment by deenine** [comment]
@gavinbenda looks like I guessed correctly, the ID3 tag was causing the 'cant play' issue with some mp3 tracks - stripping the ID3v2 tag with `id3convert -s -2 <file.mp3>` means they play when transferred to the rh1. I think ffmpeg can manipulate id3, so we should be able to ditch the mp3-wav-mp3 conversion and speed transfers up significantly.

Still working on windows build, lol.

@Invictaz thanks for all your comments. This build has working upload/download of mp3, plus at3/at3+/lpcm transfer from the device to PC, feel free to pull it down and give it a try if you have a mac. We wont have at3/at3+/lpcm transfer to the device for a while, maybe ever, unless the linux-minidisc team release a patch that supports it in the near-term.

**Comment by Invictaz** [comment]
@deenine thanks for the efforts. Now the software is almost on par with what QHiMDTransfer achieved 9 years ago lol.
Albeit in a much more modern jacket with Electron. I hope you can also pull request it to @cybercase his WebMinidisc project.

Sadly I only have a 10.11 Hackintosh. So I'm waiting for the Windows build yes. 
LPCM transfers are they also severly encrypted? 

I thought only AT3+?

Last question: does it also transfer the files which were recorded on another system (the so called: strong encryption tracks)?

**Review by Invictaz — COMMENTED** [review]
This must be one of the last checkpoints before a new release 👍

**Comment by deenine** [comment]
@Invictaz yes its getting pretty close. Feel free to pull it down and give it a test if you have a himd device (I think only MZ-RH devices are supported, but it would be good to test with NH devices):
```
git clone https://github.com/deenine/platinum-md
cd platinum-md
git checkout himd
yarn && yarn run dev
```

There are a couple of things that need fixing:
- write the filename as the ID3 tag into the mp3 before transfer to device, if there is no metadata set in input file (otherwise the device shows (null) - (null) as artist/title.
- There is a bug in the disc time calculation that causes it to fail with more than a certain amount of music on the disc, works ok if there are just a few tracks on disc: https://github.com/deenine/linux-minidisc/blob/himd-json/himdcli/himdcli.c#L158

**Comment by Invictaz** [comment]
@deenine I would like to test but I really need a Windows beta to test. Don't have a recent Linux build.

**Comment by deenine** [comment]
@Invictaz the above works for windows.

**Comment by Invictaz** [comment]
@deenine but there is no platinum-md updated .exe

**Comment by deenine** [comment]
@Invictaz Correct, there isnt a release build yet, but if you want to test the updates made in this branch:

1. make sure you have node.js and git installed on your system.
2. open a terminal
3. do the following commands
```
git clone https://github.com/deenine/platinum-md
cd platinum-md
git checkout himd
npm install yarn
yarn && yarn run dev
```

This clones my fork of platinum-md, checks out the branch that this PR is for, installs yarn (if you dont have it already installed globally), then runs a dev version of platinum-md (this is what 'yarn run dev' does).

The platinum-md window will appear and it *should* function exactly the same as if you had installed platinum-md using a exe package, except you will get the version from this fork. The nice thing about running this via the dev build is it leaves your normal platinum-md install untouched.

If you want to close it, close the window then hit ctrl-c in the terminal.

To update if further changes are made to this fork, do;
```
git remote update
git pull
```

**Comment by Invictaz** [comment]
@deenine AFAIK there is no way to install yarn on Windows?

**Comment by deenine** [comment]
@Invictaz it is definitely possible on windows 10, that is how i have been testing this on windows. I am fairly sure I just installed it with `npn install -g yarn` but it was a while ago

**Comment by Invictaz** [comment]
Due to technicus limitations I'm stuck on Windows 7 for now. So I hope it will work on that. Windows 10 has a Linux subsystem which 7 does not have.

**Comment by deenine** [comment]
@Invictaz before you spend too much time on this, I've just tried to test the windows build and it looks like I broke it this morning :( I'll tag you once I have fixed it, probably tomorrow.

In the mean time, if you do the above steps and dont checkout the himd-json branch, you should be able to run a dev build of the current master.

**Comment by Invictaz** [comment]
@deenine You didn't mention that I had to install VS 2019 + Buildtools making it a total of 7 gigabytes prior to launching it
Wow, that's massive. After I managed to install that all I get this. So apparently it's not fully working now. 

image


image

**Comment by deenine** [comment]
@Invictaz Sorry, I dont remember having to install that, but it was a long time ago when I set up my windows laptop. 

Make sure you are using the latest version, I thought I fixed this issue in the most recent patch:
```
git remote update
git pull
```

If that doesnt work, manually install check-disk-space:
`npm install check-disk-space`

then do
```
yarn
yarn run dev
```

There is an issue with netmd support right now, but I have tested himd functionality on windows 10 and osx 10.15.7. Netmd will be fixed soon.

**Comment by Invictaz** [comment]
@deenine Seems to work now. Was quite a hassle to setup. Will test it out soon. Hope you will fix the ATRAC3 issues.

image

**Comment by deenine** [comment]
@Invictaz Ive fixed the netmd issue, that seems to be working reliably now and I have tested on windows with JE780 and RH1.

Note if you are running the test version, you will need to go into the settings and tick all relevant boxes every time, because it does not persist the options and the defaults may not be sensible (must check this).

@gavinbenda I think this is fairly close to being ready to merge.

**Comment by gavinbenda** [comment]
Thanks! Have now also given it a test with an MZ-NH1 too, and it looks like it is all working quite well.
Will merge in shortly, and then do a few UI tweaks to the settings screen, etc.

**Pull request merged**
