### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by dwhinham**
This series of commits basically gets `platinum-md` up and running on Windows:

image

Some fixes to do with path handling were required, and I created a fork of [`linux-minidisc`](https://github.com/dwhinham/linux-minidisc) that allows you to build `netmdcli` more easily and natively (MinGW not required) using CMake.

Details about the binaries are provided in the commit message.

I'm aware you are exploring other approaches of getting binaries, at least for ffmpeg, so feel free to just cherry-pick what you think's useful if you would rather not commit more binaries to the repo.

I stopped short of updating the AppVeyor configuration - there are problems getting this built to do with the packages (mainly electron) being old and suffering from build-related bugs on Windows CI systems, but that's another topic. 😃

### CODE REVIEW

**Comment by Invictaz** [comment]
This is amazing work. I was hoping for a long time that this was going to happen. QHiMDTransfer isn't particularly well developed on Windows the last years.

**Comment by gavinbenda** [comment]
Oh very nice, thanks! I have a reasonably big release coming out shortly, I'll try merge this in for that, just need to do some testing and refactor a bit of code that has probably changed since your changes.

Good timing too, just got a windows machine setup to test on.

**Comment by gavinbenda** [comment]
@dwhinham what platform did you compile netmdcli for?
I tried to run it on a Surfacebook running Windows 10 Pro 64bit and couldn't get it to work, thinking it's compiled for 32bit?

**Comment by dwhinham** [comment]
It's compiled for 32bit (for compatibility), but this shouldn't be the problem - I'm running 64bit Windows 10 too.

What error message do you get? Are all the DLLs present, and did you use Zadig to replace the NetMD device's driver with a WinUSB driver?

**Comment by gavinbenda** [comment]
https://github.com/gavinbenda/platinum-md/tree/develop/resources/win/bin
I just tried to run the .exe from the windows command line and it crashed.

**Comment by dwhinham** [comment]
Apologies, the .exe is looking for a DLL in a path that only exists on my system.

Hold tight, I'm on it. :)

**Comment by dwhinham** [comment]
Please pull and re-test 😃

**Comment by gavinbenda** [comment]
Woo-hoo, that is now working great - SP uploads looking good, don't suppose there would be a similar issue with the atracdenc exec ?

**Comment by dwhinham** [comment]
There shouldn't be, but I think you have another issue (I was going to open another as I don't think this should be Windows-specific):

https://github.com/gavinbenda/platinum-md/blob/5dcd02d1847b4c06709eba2d735ae4dbc406ff06/src/renderer/components/LandingPage/DirectoryListing.vue#L269-L272

Why do we conditionally flip between 8 and 16 bit here? We probably don't want to send `atracdenc` an 8bit PCM file - IIRC, from my testing it only likes 16bit, apart from the unnecessary quality loss. This should probably always be `pcm_s16le`.

See if that gets it working :)

**Comment by gavinbenda** [comment]
Good pick up, have adjusted that, but still no difference unfortunately on windows (works on Mac).

I'm getting `Fatal error: unsupported samaple format, The operation completed successfully` which is quite strange, as that spelling mistake isn't anywhere in the current atracdenc codebase.

**Comment by dwhinham** [comment]
The Windows binary was built from the latest `atracdenc` master, commit hash `e16e9c60a18e4b914f5cb16463ed781f09808a25`.

If it's behaving differently on different platforms, there's a bug in `atracdenc` somewhere.

I can look into it if you attach an example file that works on Mac but fails on Windows.

**Comment by Invictaz** [comment]
@dcherednik might have an idea where it fails?

**Comment by gavinbenda** [comment]
Got if figured out, seems like there is a issue with fluent-ffmpeg not applying the right codec info - all working now, so will push a build out shortly.

Thanks for the help!

**Comment by gavinbenda** [comment]
https://github.com/gavinbenda/platinum-md/releases/tag/v0.7.0-alpha has been released that should have all of your changes included. Thanks again.

**Comment by dwhinham** [comment]
Great, glad it helped! 😄

**Pull request closed without merging**
